// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA3Y7YEMTCLo2ou1ixYWWPPMPYx1DmTLs',
    appId: '1:830284923974:web:53896967856013d734f647',
    messagingSenderId: '830284923974',
    projectId: 'hams-social-app',
    authDomain: 'hams-social-app.firebaseapp.com',
    storageBucket: 'hams-social-app.firebasestorage.app',
    databaseURL: 'https://hams-social-app-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkBvj47e5ex2J4lUQnPLepNnK6YhKNGvY',
    appId: '1:830284923974:android:b85dd8565736e76a34f647',
    messagingSenderId: '830284923974',
    projectId: 'hams-social-app',
    storageBucket: 'hams-social-app.firebasestorage.app',
    databaseURL: 'https://hams-social-app-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA3Y7YEMTCLo2ou1ixYWWPPMPYx1DmTLs',
    appId: '1:830284923974:web:4bb0d1aa2a42a92b34f647',
    messagingSenderId: '830284923974',
    projectId: 'hams-social-app',
    authDomain: 'hams-social-app.firebaseapp.com',
    storageBucket: 'hams-social-app.firebasestorage.app',
    databaseURL: 'https://hams-social-app-default-rtdb.firebaseio.com',
  );
}
